### ISSUE TITLE
Run in browser

### ISSUE THREAD

**Issue by joaoritter** [chesstrian/JSCryptor#18]
Is there a browser version???

**Comment by chesstrian** [comment]
The main RNCryptor project has a [Javascript implementation](https://github.com/RNCryptor/rncryptor-js) of the algorithm which is supposed to run on browsers.

Initially I decided not to check if it was possible to implement a browser version because if you have the password on client side, anybody with access to such client can get it and decrypt your data. It's  better to implement a service on server side which receives the data and return it encrypted.
